version: '3.8'

services:
  esg-ai-viewer:
    build: .
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_AUTHORITY=${AUTH_AUTHORITY}
      - AUTH_REDIRECT_URI=${AUTH_REDIRECT_URI}
    restart: unless-stopped 