apiVersion: v1
kind: Service
metadata:
  name: esg-ai-viewer
  namespace: n8n
spec:
  selector:
    app: esg-ai-viewer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP 