apiVersion: v1
kind: Service
metadata:
  name: esg-ai-viewer
  namespace: n8n
spec:
  selector:
    app: esg-ai-viewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 