apiVersion: v1
kind: ServiceAccount
metadata:
  name: esg-ai-viewer-sa
  namespace: n8n
  annotations:
    azure.workload.identity/client-id: "7ae14255-f90e-4bb0-81c7-4ed298e95248"
    azure.workload.identity/tenant-id: "fcc16827-3d82-4edf-9dc2-5d034f97127e" 