apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    # Use a safer annotation to set Content-Security-Policy
    nginx.ingress.kubernetes.io/csp: "frame-ancestors 'self' http://localhost:4200"
    # Add other recommended security headers
    nginx.ingress.kubernetes.io/add-header-X-Content-Type-Options: "nosniff"
    nginx.ingress.kubernetes.io/add-header-Referrer-Policy: "strict-origin-when-cross-origin"
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.sheltononline.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 5678
  tls:
  - hosts:
    - n8n.sheltononline.com
    secretName: n8n-tls