apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: frame-ancestors 'self' http://localhost:4200 https://your-app-domain.com";
      more_set_headers "X-Frame-Options: ALLOW-FROM http://localhost:4200 https://your-app-domain.com";
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.sheltononline.com  # Replace with your domain from Step 1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 80
  tls:
  - hosts:
    - n8n.sheltononline.com  # Replace with your domain
    secretName: n8n-tls