apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: pgAdmin
  POSTGRES_PASSWORD: pgAdm1n
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: pgUser
  POSTGRES_NON_ROOT_PASSWORD: pgUser