apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: n8n
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: n8n
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ESG AI Viewer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>ESG AI Viewer</h1>
        <p>Welcome to the ESG AI Viewer application.</p>
    </body>
    </html> 