apiVersion: v1
kind: ConfigMap
metadata:
  name: esg-ai-viewer-config
  namespace: n8n
data:
  config.json: |
    {
      "auth": {
        "clientId": "200b5caf-1971-4d5c-9d82-2a2b1dadc626",
        "authority": "https://login.microsoftonline.com/fcc16827-3d82-4edf-9dc2-5d034f97127e",
        "redirectUri": "https://esgaiviewer.sheltononline.com",
        "postLogoutRedirectUri": "https://esgaiviewer.sheltononline.com",
        "navigateToLoginRequestUrl": true,
        "cacheLocation": "localStorage",
        "scopes": ["user.read", "openid", "profile", "email"]
      },
      "buildInfo": {
        "buildTag": "20250429-011608",
        "environment": "Production"
      }
    } 