apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: n8n
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: n8n
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ESG AI Viewer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>ESG AI Viewer</h1>
        <p>Welcome to the ESG AI Viewer application.</p>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esg-ai-viewer-config
  namespace: n8n
data:
  config.json: |
    {
      "environment": "Production",
      "envName": "prod",
      "allowImportTab": false,
      "auth": {
        "clientId": "200b5caf-1971-4d5c-9d82-2a2b1dadc626",
        "authority": "https://login.microsoftonline.com/fcc16827-3d82-4edf-9dc2-5d034f97127e",
        "redirectUri": "https://esgaiviewer.sheltononline.com",
        "postLogoutRedirectUri": "https://esgaiviewer.sheltononline.com",
        "navigateToLoginRequestUrl": true,
        "cacheLocation": "localStorage",
        "scopes": ["user.read", "openid", "profile", "email"]
      }
    } 