apiVersion: apps/v1
kind: Deployment
metadata:
  name: esg-ai-viewer
  labels:
    app: esg-ai-viewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esg-ai-viewer
  template:
    metadata:
      labels:
        app: esg-ai-viewer
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: esg-ai-viewer-config
      containers:
      - name: esg-ai-viewer
        image: esgai.azurecr.io/esg-ai-viewer:latest
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/assets/config
        env:
        - name: NODE_ENV
          value: "production"
        - name: WEBHOOK_URL
          value: "http://n8n.sheltononline.com"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10 