apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: n8n
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        # Serve static assets and return 404 if not found
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|map)$ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }

        # Main app route fallback for client-side routing
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Proxy webhook requests to the public n8n instance
        location /webhook/ {
            proxy_pass http://n8n:80/webhook/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    } 